version: 2
jobs:
  build:
    working_directory: ~/mern-starter
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: alfredwhelan/dockerce:1.0
    steps:
      - checkout
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t alfredwhelan/dockerce:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push alfredwhelan/dockerce:$TAG